stages:
  - test

test-job:
  services:
    - name: docker:29.4.1-dind
      command: [ "--tls=false" ]
  variables:
    DOCKER_TLS_CERTDIR: ""
    DOCKER_HOST: "tcp://127.0.0.1:2375"
  stage: test
  script:
    - echo "Running tests..."
    - docker info
